// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetClinic.Infrastructure.Data;

#nullable disable

namespace PetClinic.Infrastructure.Migrations
{
    [DbContext(typeof(PetClinicDbContext))]
    [Migration("20260228130045_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("PetClinic.Domain.Owners.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("telephone");

                    b.HasKey("Id");

                    b.HasIndex("LastName")
                        .HasDatabaseName("owners_last_name");

                    b.ToTable("owners", (string)null);
                });

            modelBuilder.Entity("PetClinic.Domain.Owners.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("birth_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("owner_id");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type_id");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("pets_name");

                    b.HasIndex("OwnerId");

                    b.HasIndex("TypeId");

                    b.ToTable("pets", (string)null);
                });

            modelBuilder.Entity("PetClinic.Domain.Owners.PetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("types_name");

                    b.ToTable("types", (string)null);
                });

            modelBuilder.Entity("PetClinic.Domain.Owners.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("visit_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("PetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pet_id");

                    b.HasKey("Id");

                    b.HasIndex("PetId")
                        .HasDatabaseName("visits_pet_id");

                    b.ToTable("visits", (string)null);
                });

            modelBuilder.Entity("PetClinic.Domain.Vets.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("specialties_name");

                    b.ToTable("specialties", (string)null);
                });

            modelBuilder.Entity("PetClinic.Domain.Vets.Vet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.HasKey("Id");

                    b.HasIndex("LastName")
                        .HasDatabaseName("vets_last_name");

                    b.ToTable("vets", (string)null);
                });

            modelBuilder.Entity("SpecialtyVet", b =>
                {
                    b.Property<int>("SpecialtiesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SpecialtiesId", "VetId");

                    b.HasIndex("VetId");

                    b.ToTable("vet_specialties", (string)null);
                });

            modelBuilder.Entity("PetClinic.Domain.Owners.Pet", b =>
                {
                    b.HasOne("PetClinic.Domain.Owners.Owner", null)
                        .WithMany("Pets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetClinic.Domain.Owners.PetType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PetClinic.Domain.Owners.Visit", b =>
                {
                    b.HasOne("PetClinic.Domain.Owners.Pet", null)
                        .WithMany("Visits")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpecialtyVet", b =>
                {
                    b.HasOne("PetClinic.Domain.Vets.Specialty", null)
                        .WithMany()
                        .HasForeignKey("SpecialtiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetClinic.Domain.Vets.Vet", null)
                        .WithMany()
                        .HasForeignKey("VetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetClinic.Domain.Owners.Owner", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("PetClinic.Domain.Owners.Pet", b =>
                {
                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
